### ISSUE TITLE
question about eq.(12) in your paper.

### ISSUE THREAD

**Issue by zzd1992** [siavashBigdeli/DMSP#1]
I am confused about eq.(12) in your paper.
What is the gradient operator w.r.t? x or eta?
In context, it should be w.r.t x. 
However, I think if it is w.r.t x, the first equal-sign looks false.
Can you explain it in detail? Thanks.

**Comment by siavashBigdeli** [comment]
Sorry for the late response.
The first equality sign of the Eq.12 holds by the definition of the Gaussian derivatives, which is wrt. eta.
In the second equality, since the integral is a convolution, we can switch the gradients to be wrt. variable x (see [convolution and differentiation](https://en.wikipedia.org/wiki/Convolution#Properties)).
Then using the [Leibniz rule of integrals](https://en.wikipedia.org/wiki/Leibniz_integral_rule) we can move gradients outside of the integral.
Hope this helps!
